package com.example.demo.domain.escola;

public enum CategoriaEscola {
    ESCOLA_DE_EDUCACAO,
    CULTURA_E_HUMANIDADE,
    ESCOLA_DE_CIENCIAS_SOCIAIS_E_APLICADAS,
    ESCOLA_DE_ENGENARIA_E_CIENCIAS_TECNOLOGICAS,
    ESCOLA_DE_CIENCIAS_NATURAIS_E_DA_SAUDE
}
