spring.application.name=demo
jwt.secret=kg2OTmb0NRhLzS7ZfluwbEkU4cJNcC0jPVnmJCUrvUiieRUhB21WCG2g6d6n8GW3


spring.h2.console.enabled=true

spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:h2:mem:testdb
#logging.level.org.springframework.security=DEBUG
#logging.level.io.jsonwebtoken=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

